#if !canImport(ObjectiveC)
import XCTest

extension GraphQLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GraphQLTests = [
        ("testBooleanValue", testBooleanValue),
        ("testDigit", testDigit),
        ("testEnumValue", testEnumValue),
        ("testExponentIndicator", testExponentIndicator),
        ("testExponentPart", testExponentPart),
        ("testFloatValue", testFloatValue),
        ("testFractionalPart", testFractionalPart),
        ("testIntValue", testIntValue),
        ("testListValue", testListValue),
        ("testName", testName),
        ("testNegativeSign", testNegativeSign),
        ("testnonZeroDigit", testnonZeroDigit),
        ("testNullValue", testNullValue),
        ("testObjectValue", testObjectValue),
        ("testSign", testSign),
        ("testStringValue", testStringValue),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GraphQLTests.__allTests__GraphQLTests),
    ]
}
#endif
