#if !canImport(ObjectiveC)
import XCTest

extension GraphQLParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GraphQLParserTests = [
        ("testAliases", testAliases),
        ("testArguments", testArguments),
        ("testArgumentsField", testArgumentsField),
        ("testDirectives", testDirectives),
        ("testFields", testFields),
        ("testFragments", testFragments),
        ("testFragmentsWithVariables", testFragmentsWithVariables),
        ("testInlineFragment", testInlineFragment),
        ("testMetaFields", testMetaFields),
        ("testMutations", testMutations),
        ("testOperationName", testOperationName),
        ("testVariables", testVariables),
        ("testVariablesDefault", testVariablesDefault),
    ]
}

extension GraphQLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GraphQLTests = [
        ("testAlias", testAlias),
        ("testArgument", testArgument),
        ("testArguments", testArguments),
        ("testBooleanValue", testBooleanValue),
        ("testDefaultValue", testDefaultValue),
        ("testDigit", testDigit),
        ("testDirective", testDirective),
        ("testDirectives", testDirectives),
        ("testDocument", testDocument),
        ("testEnumValue", testEnumValue),
        ("testExecutableDefinition", testExecutableDefinition),
        ("testExponentIndicator", testExponentIndicator),
        ("testExponentPart", testExponentPart),
        ("testField", testField),
        ("testFloatValue", testFloatValue),
        ("testFractionalPart", testFractionalPart),
        ("testFragmentDefinition", testFragmentDefinition),
        ("testFragmentName", testFragmentName),
        ("testFragmentSpread", testFragmentSpread),
        ("testInlineFragment", testInlineFragment),
        ("testIntValue", testIntValue),
        ("testListType", testListType),
        ("testListValue", testListValue),
        ("testName", testName),
        ("testNegativeSign", testNegativeSign),
        ("testNonNullType", testNonNullType),
        ("testnonZeroDigit", testnonZeroDigit),
        ("testNullValue", testNullValue),
        ("testObjectField", testObjectField),
        ("testObjectValue", testObjectValue),
        ("testOperationDefinition", testOperationDefinition),
        ("testOperationType", testOperationType),
        ("testSelection", testSelection),
        ("testSign", testSign),
        ("testStringValue", testStringValue),
        ("testTypeCondition", testTypeCondition),
        ("testVariable", testVariable),
        ("testVariableDefinition", testVariableDefinition),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GraphQLParserTests.__allTests__GraphQLParserTests),
        testCase(GraphQLTests.__allTests__GraphQLTests),
    ]
}
#endif
