#if !canImport(ObjectiveC)
import XCTest

extension GraphQLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GraphQLTests = [
        ("testArgument", testArgument),
        ("testArguments", testArguments),
        ("testBooleanValue", testBooleanValue),
        ("testDefaultValue", testDefaultValue),
        ("testDigit", testDigit),
        ("testDirective", testDirective),
        ("testDirectives", testDirectives),
        ("testEnumValue", testEnumValue),
        ("testExponentIndicator", testExponentIndicator),
        ("testExponentPart", testExponentPart),
        ("testFloatValue", testFloatValue),
        ("testFractionalPart", testFractionalPart),
        ("testIntValue", testIntValue),
        ("testListType", testListType),
        ("testListValue", testListValue),
        ("testName", testName),
        ("testNegativeSign", testNegativeSign),
        ("testNonNullType", testNonNullType),
        ("testnonZeroDigit", testnonZeroDigit),
        ("testNullValue", testNullValue),
        ("testObjectField", testObjectField),
        ("testObjectValue", testObjectValue),
        ("testSign", testSign),
        ("testStringValue", testStringValue),
        ("testVariable", testVariable),
        ("testVariableDefinition", testVariableDefinition),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GraphQLTests.__allTests__GraphQLTests),
    ]
}
#endif
